# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'databasecommand.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 450)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setStyleSheet("")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addWidget(self.widget_5)
        self.verticalLayout.setStretch(0, 7)
        self.verticalLayout.setStretch(1, 3)
        self.horizontalLayout.addWidget(self.widget_2)
        self.horizontalLayout.setStretch(0, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 23))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_E = QtWidgets.QMenu(self.menubar)
        self.menu_E.setObjectName("menu_E")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionShear = QtWidgets.QAction(MainWindow)
        self.actionShear.setObjectName("actionShear")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")
        self.actionChange = QtWidgets.QAction(MainWindow)
        self.actionChange.setObjectName("actionChange")
        self.actionSelectAll = QtWidgets.QAction(MainWindow)
        self.actionSelectAll.setObjectName("actionSelectAll")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionT_New = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/editor/images/new_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_New.setIcon(icon)
        self.actionT_New.setText("")
        self.actionT_New.setObjectName("actionT_New")
        self.actionT_Open = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/editor/images/open_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Open.setIcon(icon1)
        self.actionT_Open.setText("")
        self.actionT_Open.setObjectName("actionT_Open")
        self.actionT_Save = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/editor/images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Save.setIcon(icon2)
        self.actionT_Save.setText("")
        self.actionT_Save.setObjectName("actionT_Save")
        self.actionT_Copy = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/editor/images/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Copy.setIcon(icon3)
        self.actionT_Copy.setText("")
        self.actionT_Copy.setObjectName("actionT_Copy")
        self.actionT_Paste = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/editor/images/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Paste.setIcon(icon4)
        self.actionT_Paste.setText("")
        self.actionT_Paste.setObjectName("actionT_Paste")
        self.actionT_Shear = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/editor/images/shear.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Shear.setIcon(icon5)
        self.actionT_Shear.setText("")
        self.actionT_Shear.setObjectName("actionT_Shear")
        self.actionT_Undo = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/editor/images/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Undo.setIcon(icon6)
        self.actionT_Undo.setText("")
        self.actionT_Undo.setObjectName("actionT_Undo")
        self.actionT_Redo = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/editor/images/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Redo.setIcon(icon7)
        self.actionT_Redo.setText("")
        self.actionT_Redo.setObjectName("actionT_Redo")
        self.actionT_Bold = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/editor/images/bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Bold.setIcon(icon8)
        self.actionT_Bold.setText("")
        self.actionT_Bold.setObjectName("actionT_Bold")
        self.actionT_Incline = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/editor/images/incline.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Incline.setIcon(icon9)
        self.actionT_Incline.setText("")
        self.actionT_Incline.setObjectName("actionT_Incline")
        self.actionT_Underline = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/editor/images/underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Underline.setIcon(icon10)
        self.actionT_Underline.setText("")
        self.actionT_Underline.setObjectName("actionT_Underline")
        self.actionT_Lower2upper = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/editor/images/lower2upper.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Lower2upper.setIcon(icon11)
        self.actionT_Lower2upper.setText("")
        self.actionT_Lower2upper.setObjectName("actionT_Lower2upper")
        self.actionT_Upper2lower = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/editor/images/upper2lower.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Upper2lower.setIcon(icon12)
        self.actionT_Upper2lower.setText("")
        self.actionT_Upper2lower.setObjectName("actionT_Upper2lower")
        self.actionaT_Alignleft = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/editor/images/alignleft.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionaT_Alignleft.setIcon(icon13)
        self.actionaT_Alignleft.setText("")
        self.actionaT_Alignleft.setObjectName("actionaT_Alignleft")
        self.actionaT_Aligncenter = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/editor/images/aligncenter.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionaT_Aligncenter.setIcon(icon14)
        self.actionaT_Aligncenter.setText("")
        self.actionaT_Aligncenter.setObjectName("actionaT_Aligncenter")
        self.actionaT_Alignright = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/editor/images/alignright.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionaT_Alignright.setIcon(icon15)
        self.actionaT_Alignright.setText("")
        self.actionaT_Alignright.setObjectName("actionaT_Alignright")
        self.actionT_Font = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/editor/images/font.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Font.setIcon(icon16)
        self.actionT_Font.setText("")
        self.actionT_Font.setObjectName("actionT_Font")
        self.actionT_Color = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/editor/images/font_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Color.setIcon(icon17)
        self.actionT_Color.setText("")
        self.actionT_Color.setObjectName("actionT_Color")
        self.actionT_Pattern = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/editor/images/pattern_switch.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Pattern.setIcon(icon18)
        self.actionT_Pattern.setText("")
        self.actionT_Pattern.setObjectName("actionT_Pattern")
        self.actionT_Execution = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/editor/images/execution.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionT_Execution.setIcon(icon19)
        self.actionT_Execution.setObjectName("actionT_Execution")
        self.menu_F.addAction(self.actionNew)
        self.menu_F.addAction(self.actionOpen)
        self.menu_F.addAction(self.actionSave)
        self.menu_F.addAction(self.actionSaveAs)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actionPrint)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actionExit)
        self.menu_E.addAction(self.actionUndo)
        self.menu_E.addAction(self.actionRedo)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.actionShear)
        self.menu_E.addAction(self.actionCopy)
        self.menu_E.addAction(self.actionPaste)
        self.menu_E.addAction(self.actionDelete)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.actionFind)
        self.menu_E.addAction(self.actionChange)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.actionSelectAll)
        self.menu_H.addAction(self.actionHelp)
        self.menu_H.addAction(self.actionAbout)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_E.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())
        self.toolBar.addAction(self.actionT_New)
        self.toolBar.addAction(self.actionT_Open)
        self.toolBar.addAction(self.actionT_Save)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionT_Copy)
        self.toolBar.addAction(self.actionT_Paste)
        self.toolBar.addAction(self.actionT_Shear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionT_Execution)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionT_Undo)
        self.toolBar.addAction(self.actionT_Redo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionT_Bold)
        self.toolBar.addAction(self.actionT_Incline)
        self.toolBar.addAction(self.actionT_Underline)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionT_Lower2upper)
        self.toolBar.addAction(self.actionT_Upper2lower)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionaT_Alignleft)
        self.toolBar.addAction(self.actionaT_Aligncenter)
        self.toolBar.addAction(self.actionaT_Alignright)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionT_Font)
        self.toolBar.addAction(self.actionT_Color)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionT_Pattern)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setStatusTip(_translate("MainWindow", "状态栏"))
        self.menu_F.setTitle(_translate("MainWindow", "文件"))
        self.menu_E.setTitle(_translate("MainWindow", "编辑"))
        self.menu_H.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "新建(&N)"))
        self.actionNew.setIconText(_translate("MainWindow", "新建(N)"))
        self.actionNew.setStatusTip(_translate("MainWindow", "新建一个文本"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "打开(&O)"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "打开一个文本"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "保存(&S)"))
        self.actionSave.setStatusTip(_translate("MainWindow", "保存这个文本"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "另存为(&A)"))
        self.actionSaveAs.setStatusTip(_translate("MainWindow", "文本另存为"))
        self.actionPrint.setText(_translate("MainWindow", "打印(&P)"))
        self.actionPrint.setStatusTip(_translate("MainWindow", "打印这个文本"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionExit.setText(_translate("MainWindow", "退出(&X)"))
        self.actionExit.setStatusTip(_translate("MainWindow", "退出界面"))
        self.actionUndo.setText(_translate("MainWindow", "撤销(&U)"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "重做(&R)"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionShear.setText(_translate("MainWindow", "剪切(&T)"))
        self.actionShear.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "复制(&C)"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "粘贴(&P)"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionDelete.setText(_translate("MainWindow", "删除(&L)"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Del"))
        self.actionFind.setText(_translate("MainWindow", "查找(&F)"))
        self.actionFind.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionChange.setText(_translate("MainWindow", "替换(&H)"))
        self.actionChange.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionSelectAll.setText(_translate("MainWindow", "全选(&A)"))
        self.actionSelectAll.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionHelp.setText(_translate("MainWindow", "查看帮助(&H)"))
        self.actionHelp.setShortcut(_translate("MainWindow", "Shift+H"))
        self.actionAbout.setText(_translate("MainWindow", "关于记事本(&A)"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Shift+A"))
        self.actionT_New.setToolTip(_translate("MainWindow", "新建"))
        self.actionT_New.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionT_Open.setToolTip(_translate("MainWindow", "打开"))
        self.actionT_Open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionT_Save.setToolTip(_translate("MainWindow", "保存"))
        self.actionT_Save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionT_Copy.setToolTip(_translate("MainWindow", "复制"))
        self.actionT_Copy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionT_Paste.setToolTip(_translate("MainWindow", "粘贴"))
        self.actionT_Paste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionT_Shear.setToolTip(_translate("MainWindow", "剪切"))
        self.actionT_Shear.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionT_Undo.setToolTip(_translate("MainWindow", "撤销"))
        self.actionT_Undo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionT_Redo.setToolTip(_translate("MainWindow", "重做"))
        self.actionT_Redo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionT_Bold.setToolTip(_translate("MainWindow", "粗体"))
        self.actionT_Bold.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionT_Incline.setToolTip(_translate("MainWindow", "倾斜"))
        self.actionT_Incline.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionT_Underline.setToolTip(_translate("MainWindow", "下划线"))
        self.actionT_Underline.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionT_Lower2upper.setToolTip(_translate("MainWindow", "转大写"))
        self.actionT_Upper2lower.setToolTip(_translate("MainWindow", "转小写"))
        self.actionaT_Alignleft.setToolTip(_translate("MainWindow", "居左"))
        self.actionaT_Alignleft.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionaT_Aligncenter.setToolTip(_translate("MainWindow", "居中"))
        self.actionaT_Aligncenter.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionaT_Alignright.setToolTip(_translate("MainWindow", "居右"))
        self.actionaT_Alignright.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionT_Font.setToolTip(_translate("MainWindow", "字体"))
        self.actionT_Font.setShortcut(_translate("MainWindow", "Ctrl+Shift+F"))
        self.actionT_Color.setToolTip(_translate("MainWindow", "颜色"))
        self.actionT_Color.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionT_Pattern.setToolTip(_translate("MainWindow", "切换模式"))
        self.actionT_Execution.setText(_translate("MainWindow", "execution"))
        self.actionT_Execution.setToolTip(_translate("MainWindow", "执行"))
import my_images_rc
